# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'SVProgressHUD'
pod 'Google/Analytics'
target 'Blox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Blox

  target 'BloxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BloxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
